[2022-04-30 12:42:29 +0800] [1] [INFO] Starting gunicorn 20.0.4
[2022-04-30 12:42:29 +0800] [1] [INFO] Listening at: http://0.0.0.0:17001 (1)
[2022-04-30 12:42:29 +0800] [1] [INFO] Using worker: sync
[2022-04-30 12:42:29 +0800] [15] [INFO] Booting worker with pid: 15
[2022-04-30 12:42:29 +0800] [16] [INFO] Booting worker with pid: 16
[2022-04-30 12:42:29 +0800] [17] [INFO] Booting worker with pid: 17
[2022-04-30 12:42:29 +0800] [18] [INFO] Booting worker with pid: 18
[2022-04-30 12:42:59 +0800] [1] [CRITICAL] WORKER TIMEOUT (pid:15)
[2022-04-30 12:42:59 +0800] [15] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/app/app.py", line 10, in <module>
    from face_detect import check
  File "/app/face_detect.py", line 2, in <module>
    import dlib
  File "/usr/local/lib/python3.9/site-packages/dlib/__init__.py", line 19, in <module>
    from _dlib_pybind11 import *
ImportError: SystemExit: 1

At:
  /usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py(201): handle_abort
  <frozen importlib._bootstrap>(228): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(1173): create_module
  <frozen importlib._bootstrap>(565): module_from_spec
  <frozen importlib._bootstrap>(666): _load_unlocked
  <frozen importlib._bootstrap>(986): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1007): _find_and_load
  /usr/local/lib/python3.9/site-packages/dlib/__init__.py(19): <module>
  <frozen importlib._bootstrap>(228): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(850): exec_module
  <frozen importlib._bootstrap>(680): _load_unlocked
  <frozen importlib._bootstrap>(986): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1007): _find_and_load
  /app/face_detect.py(2): <module>
  <frozen importlib._bootstrap>(228): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(850): exec_module
  <frozen importlib._bootstrap>(680): _load_unlocked
  <frozen importlib._bootstrap>(986): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1007): _find_and_load
  /app/app.py(10): <module>
  <frozen importlib._bootstrap>(228): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(850): exec_module
  <frozen importlib._bootstrap>(680): _load_unlocked
  <frozen importlib._bootstrap>(986): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1007): _find_and_load
  <frozen importlib._bootstrap>(1030): _gcd_import
  /usr/local/lib/python3.9/importlib/__init__.py(127): import_module
  /usr/local/lib/python3.9/site-packages/gunicorn/util.py(358): import_app
  /usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py(39): load_wsgiapp
  /usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py(49): load
  /usr/local/lib/python3.9/site-packages/gunicorn/app/base.py(67): wsgi
  /usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py(144): load_wsgi
  /usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py(119): init_process
  /usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py(583): spawn_worker
  /usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py(616): spawn_workers
  /usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py(545): manage_workers
  /usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py(202): run
  /usr/local/lib/python3.9/site-packages/gunicorn/app/base.py(72): run
  /usr/local/lib/python3.9/site-packages/gunicorn/app/base.py(228): run
  /usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py(58): run
  /usr/local/bin/gunicorn(8): <module>

[2022-04-30 12:42:59 +0800] [15] [INFO] Worker exiting (pid: 15)
[2022-04-30 12:43:00 +0800] [1] [CRITICAL] WORKER TIMEOUT (pid:16)
[2022-04-30 12:43:00 +0800] [1] [CRITICAL] WORKER TIMEOUT (pid:17)
[2022-04-30 12:43:00 +0800] [1] [CRITICAL] WORKER TIMEOUT (pid:18)
[2022-04-30 12:43:00 +0800] [18] [INFO] Worker exiting (pid: 18)
[2022-04-30 12:43:02 +0800] [48] [INFO] Booting worker with pid: 48
[2022-04-30 12:43:02 +0800] [47] [INFO] Booting worker with pid: 47
[2022-04-30 12:43:02 +0800] [49] [INFO] Booting worker with pid: 49
[2022-04-30 12:43:03 +0800] [50] [INFO] Booting worker with pid: 50
[2022-04-30 12:43:31 +0800] [1] [CRITICAL] WORKER TIMEOUT (pid:47)
[2022-04-30 12:43:32 +0800] [1] [CRITICAL] WORKER TIMEOUT (pid:48)
[2022-04-30 12:43:34 +0800] [1] [CRITICAL] WORKER TIMEOUT (pid:49)
[2022-04-30 12:43:34 +0800] [1] [CRITICAL] WORKER TIMEOUT (pid:50)
[2022-04-30 12:43:36 +0800] [79] [INFO] Booting worker with pid: 79
[2022-04-30 12:43:36 +0800] [80] [INFO] Booting worker with pid: 80
[2022-04-30 12:43:37 +0800] [81] [INFO] Booting worker with pid: 81
[2022-04-30 12:43:38 +0800] [82] [INFO] Booting worker with pid: 82
[2022-04-30 12:44:06 +0800] [1] [CRITICAL] WORKER TIMEOUT (pid:79)
[2022-04-30 12:44:07 +0800] [1] [CRITICAL] WORKER TIMEOUT (pid:80)
[2022-04-30 12:44:07 +0800] [1] [CRITICAL] WORKER TIMEOUT (pid:81)
[2022-04-30 12:44:08 +0800] [111] [INFO] Booting worker with pid: 111
[2022-04-30 12:44:08 +0800] [1] [CRITICAL] WORKER TIMEOUT (pid:82)
[2022-04-30 12:44:08 +0800] [112] [INFO] Booting worker with pid: 112
[2022-04-30 12:44:08 +0800] [113] [INFO] Booting worker with pid: 113
[2022-04-30 12:44:08 +0800] [114] [INFO] Booting worker with pid: 114
[2022-04-30 12:44:38 +0800] [1] [CRITICAL] WORKER TIMEOUT (pid:111)
[2022-04-30 12:44:38 +0800] [1] [CRITICAL] WORKER TIMEOUT (pid:112)
[2022-04-30 12:44:39 +0800] [1] [CRITICAL] WORKER TIMEOUT (pid:113)
[2022-04-30 12:44:39 +0800] [1] [CRITICAL] WORKER TIMEOUT (pid:114)
[2022-04-30 12:44:40 +0800] [143] [INFO] Booting worker with pid: 143
[2022-04-30 12:44:40 +0800] [144] [INFO] Booting worker with pid: 144
[2022-04-30 12:44:40 +0800] [145] [INFO] Booting worker with pid: 145
[2022-04-30 12:44:40 +0800] [146] [INFO] Booting worker with pid: 146
[2022-04-30 12:45:10 +0800] [1] [CRITICAL] WORKER TIMEOUT (pid:143)
[2022-04-30 12:45:10 +0800] [1] [CRITICAL] WORKER TIMEOUT (pid:144)
[2022-04-30 12:45:11 +0800] [1] [CRITICAL] WORKER TIMEOUT (pid:145)
[2022-04-30 12:45:11 +0800] [1] [CRITICAL] WORKER TIMEOUT (pid:146)
[2022-04-30 12:45:11 +0800] [175] [INFO] Booting worker with pid: 175
[2022-04-30 12:45:11 +0800] [176] [INFO] Booting worker with pid: 176
[2022-04-30 12:45:11 +0800] [177] [INFO] Booting worker with pid: 177
[2022-04-30 12:45:12 +0800] [178] [INFO] Booting worker with pid: 178
